# -*- coding: utf-8 -*-
"""Projects.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/160V8vn5DeO67CZFcXFL8lgUFwsiy6lKT

First project
"""

!pip install PyPDF2



!pip install PyPDF2

import os
import difflib
from PyPDF2 import PdfReader
from google.colab import files

# Upload PDFs
print("📂 Please upload two PDF files (from different converters).")
uploaded = files.upload()  #opens files picker in colab. - upload files are stored in a dictionary {filename : file_bytes}

# Get file names
pdf_files = list(uploaded.keys())                         #makes list of uploaded filename maintaining insertion order.
if len(pdf_files) != 2:                                   #checks that there are two files
    raise ValueError("⚠️ Please upload exactly 2 PDF files!")
pdf_file_A, pdf_file_B = pdf_files                        #gives name to both the files.

# Extract text from PDF

def extract_text(pdf_path):
    reader = PdfReader(pdf_path)           #opens the PDF file. PdfReader builds an object with .pages and .metadata
    text = ""                              #Empty string to collect all the page text
    for page in reader.pages:              #loop over each page object in the PDF.
        text += page.extract_text() or ""  #call extract_text() on each page.
    return text

# Compare text differences

def compare_texts(text_a, text_b):
    diff = difflib.unified_diff(
        text_a.splitlines(), text_b.splitlines(),
        lineterm="", n=3
    )
    print(list(diff))
    return list(diff)
# Compare metadata

def extract_metadata(pdf_path):    #reader.metadata gives you a dictionary-like object containing metadata fields commonly found in a PDF:
  reader = PdfReader(pdf_path)     #e.g., Title, Author, Producer, Creator, CreationDate, ModDate.
  return reader.metadata

# Main Comparator

def compare_pdfs(pdf_a, pdf_b):
    print("\n--- 📊 PDF Comparison Report ---")

    # File size
    size_a = os.path.getsize(pdf_a) / (1024 * 1024) #to convert bytes into megabytes
    size_b = os.path.getsize(pdf_b) / (1024 * 1024)
    print(f"File A size: {size_a:.3f} MB")
    print(f"File B size: {size_b:.3f} MB")

    # Extract texts
    text_a = extract_text(pdf_a)
    text_b = extract_text(pdf_b)

    # Text similarity matcher
    seq = difflib.SequenceMatcher(None, text_a, text_b) #SequenceMatcher compares characters in a sequence.
    similarity = seq.ratio() * 100                      #very short differences (like extra spaces, punctuation, or timestamps) can change the ratio noticeably.
    print(f"Text Similarity: {similarity:.2f}%")        #For more robust comparison you might compare at a word level (split into words)
    # Show sample differences                           #or normalize text first (lowercase, remove punctuation).
    differences = compare_texts(text_a, text_b)
    print("\n--- 📝 Text Differences (first 20 lines) ---")
    for line in differences[:20]:
        print(line)

    # Metadata
    meta_a = extract_metadata(pdf_a)
    meta_b = extract_metadata(pdf_b)
    print("\n--- ℹ️ Metadata Comparison ---")
    print("File A Metadata:", meta_a)
    print("File B Metadata:", meta_b)

# Run Comparator

compare_pdfs(pdf_file_A, pdf_file_B)

!pip install reportlab

from reportlab.lib.pagesizes import letter #letter for standard page size (8.5 X 11)
from reportlab.pdfgen import canvas #allow to draw text , lines etc..

def export_report_pdf(pdf_a, pdf_b, output_file="comparison_report.pdf"):
    from difflib import SequenceMatcher

    # Gather data again using your existing functions
    size_a = os.path.getsize(pdf_a) / (1024 * 1024) #coversion of file to MB
    size_b = os.path.getsize(pdf_b) / (1024 * 1024)
    text_a = extract_text(pdf_a)
    text_b = extract_text(pdf_b)
    seq = SequenceMatcher(None, text_a, text_b)
    similarity = seq.ratio() * 100
    differences = compare_texts(text_a, text_b)
    meta_a = extract_metadata(pdf_a)
    meta_b = extract_metadata(pdf_b)

    # Start PDF
    c = canvas.Canvas(output_file, pagesize=letter)
    width, height = letter

    # Title
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 50, "📊 PDF Comparison Report")

    c.setFont("Helvetica", 10)
    y = height - 80

    # Content lines
    lines = [
        f"File A: {pdf_a} ({size_a:.3f} MB)",
        f"File B: {pdf_b} ({size_b:.3f} MB)",
        f"Text Similarity: {similarity:.2f}%",
        "",
        "--- 📝 Text Differences (first 10 lines) ---"
    ] + differences[:10] + [
        "",
        "--- ℹ️ Metadata Comparison ---",
        f"File A Metadata: {meta_a}",
        f"File B Metadata: {meta_b}"
    ]

    # Write line by line, handle page breaks
    for line in lines:
        c.drawString(50, y, str(line)[:1000])  # avoid very long overflow
        y -= 15
        if y < 50:  # new page
            c.showPage()
            c.setFont("Helvetica", 10)
            y = height - 50

    c.save()
    print(f"\n✅ PDF Report exported to {output_file}")


# 🔹 Run this after your compare_pdfs
export_report_pdf(pdf_file_A, pdf_file_B)

from google.colab import files

# Download the generated PDF report
files.download("comparison_report.pdf")



